### ISSUE TITLE
'npm' is not recognized

### ISSUE THREAD

**Issue by bradmagnus** [NV/chrome-devtools-autosave-server#10]
When I run the command prompt "npm install -g autosave" I get:

"'npm' is not recognized as an internal or external command, operable program or batch file."

Any suggestions?

Windows 7
Intel i7

**Comment by NV** [comment]
Have you installed [Node.js](http://nodejs.org/#download)?

**Comment by bradmagnus** [comment]
Yes. I haven't restarted yet though. I'll try that.

**Comment by bradmagnus** [comment]
That's what it was. Restarting allowed it to run. Thanks!
