### ISSUE TITLE
X-URL header is missing

### ISSUE THREAD

**Issue by Anenth** [NV/chrome-devtools-autosave-server#12]
i have installed everything correctly 

but i am getting
" DevTools Autosave Server doesnâ€™t run on http://127.0.0.1:9104/save"
error 
and wen i opened http://127.0.0.1:9104/save it says X-URL header is missing

**Comment by NV** [comment]
Why did you close the issue? Have you resolved the problem?

> and wen i opened http://127.0.0.1:9104/save it says X-URL header is missing

It’s okay. Opening http://127.0.0.1:9104/ should give you "DevTools Autosave {version} running well".

> doesnâ€™t

You’re not the first one with the encoding issue. What OS do you use?

**Comment by Anenth** [comment]
the problem is resolved !
i had closed the cmd .

**Comment by benbenlijie** [comment]
I got the same problem. When I opened http://127.0.0.1:9104/save it says X-URL header is missing.  When i edit the javascript with the chrome devtools, there is nothing changed in the source file. But when i edit the css, it works. Why? And thank you very much for your great job. This is amazing tool i've ever used!

**Comment by Anenth** [comment]
u should keep the cmd open!
