### ISSUE TITLE
install autosave server offline

### ISSUE THREAD

**Issue by andytorres** [NV/chrome-devtools-autosave-server#17]
Since I am behind a proxy server, I followed your instructions to install from a folder, but it still throws an error when it tries to get commander 0.5.x. I tried to remove the dependency directly from the package.json and it insatlled, but when I execute C:\Documents and Settings\Andy>autosave, it shows this: Error: Cannot find module 'commander'.
How can I install commander the same way I installed autosave server?
Thanks, 
Andy

**Comment by NV** [comment]
I don’t know. It might be a good idea to ask this question on [npm mailing list](https://groups.google.com/forum/?fromgroups#!forum/npm-).
