### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by kriskasper** [NV/chrome-devtools-autosave-server#19]
Hi,

I get following errors when installing via cmd on Windows:

---

C:>npm install -g autosave
npm http GET https://registry.npmjs.org/autosave
npm http 200 https://registry.npmjs.org/autosave
npm http GET https://registry.npmjs.org/autosave/-/autosave-1.0.1.tgz
npm http 200 https://registry.npmjs.org/autosave/-/autosave-1.0.1.tgz
npm http GET https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/commander/-/commander-0.5.2.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-0.5.2.tgz
C:\Documents and Settings\guma\Application Data\npm\autosave -> C:\Documents and
 Settings\guma\Application Data\npm\node_modules\autosave\bin\autosave

> autosave@1.0.1 install C:\Documents and Settings\guma\Application Data\npm\nod
> e_modules\autosave
> node ./scripts/install.js

fs.js:420
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\Documents and Settings\guma\Library
\LaunchAgents'
    at Object.lstatSync (fs.js:420:18)
    at isDirectory (C:\Documents and Settings\guma\Application Data\npm\node_mod
ules\autosave\scripts\install.js:9:20)
    at Object.<anonymous> (C:\Documents and Settings\guma\Application Data\npm\n
ode_modules\autosave\scripts\install.js:3:25)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)

npm ERR! autosave@1.0.1 install: `node ./scripts/install.js`
npm ERR! `cmd "/c" "node ./scripts/install.js"` failed with 1
npm ERR!
npm ERR! Failed at the autosave@1.0.1 install script.
npm ERR! This is most likely a problem with the autosave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls autosave
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "autosave"
npm ERR! cwd C:\
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.24
npm ERR! code ELIFECYCLE
npm ERR! message autosave@1.0.1 install: `node ./scripts/install.js`
npm ERR! message `cmd "/c" "node ./scripts/install.js"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm not ok
npm not ok

---

Please help

**Comment by NV** [comment]
Should be fixed. Try `npm install -g autosave` again.

**Comment by kriskasper** [comment]
Thanks! It works now.

**Comment by manaetches** [comment]
Hi I get the following error, almost similar to the above. See below:

C:\Windows\System32>npm install -g autosave
npm http GET https://registry.npmjs.org/autosave
npm http 304 https://registry.npmjs.org/autosave
npm WARN package.json autosave@1.0.2 No README.md file found!
npm ERR! Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules\autosave'
npm ERR!  { [Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules\autosave'
]
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\Program Files\nodejs\node_modules\autosave',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: 'C:\Program Files\nodejs\node_modules\autosave',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ 'DirWriter._create (C:\Program Files\nodejs\node_modules\npm\
node_modules\fstream\lib\dir-writer.js:36:23)',
npm ERR!      'C:\Program Files\nodejs\node_modules\npm\node_modules\mkdir
p\index.js:45:53',
npm ERR!      'Object.oncomplete (fs.js:297:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "autosave"
npm ERR! cwd C:\Windows\System32
npm ERR! node -v v0.8.7
npm ERR! npm -v 1.1.49
npm ERR! path C:\Program Files\nodejs\node_modules\autosave
npm ERR! fstream_path C:\Program Files\nodejs\node_modules\autosave
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules\autosav
e'
npm ERR! fstream_stack DirWriter._create (C:\Program Files\nodejs\node_modules\n
pm\node_modules\fstream\lib\dir-writer.js:36:23)
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\mkd
irp\index.js:45:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! Error: EPERM, open 'C:\Windows\System32\npm-debug.log'
npm ERR!  { [Error: EPERM, open 'C:\Windows\System32\npm-debug.log']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\Windows\System32\npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "autosave"
npm ERR! cwd C:\Windows\System32
npm ERR! node -v v0.8.7
npm ERR! npm -v 1.1.49
npm ERR! path C:\Windows\System32\npm-debug.log
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open 'C:\Windows\System32\npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\System32\npm-debug.log
npm ERR! not ok code 0

Any idea why?
