### ISSUE TITLE
autostart script doesn't escape $HOME variable spaces

### ISSUE THREAD

**Issue by drewcovi** [NV/chrome-devtools-autosave-server#21]
The bash script for the autostart appears to use the $HOME variable, but with a (very) few mac systems (at least mine) this variable has whitespace with "/Volumes/Macintosh HD". This is entirely due to the fact that I'm nuts and use an SSD for my OS and an HDD for my home directory (performance and storage ftw).

At your discretion this issue can be fixed by simply wrapping this variable in double quotes. I realize this is a super minor issue. thanks! :)
# !/bin/sh

if [ -d "$HOME/Library/LaunchAgents/" ]; then
    # Mac OS X
    launch_agents_dir="$HOME/Library/LaunchAgents/"
    name='com.chrome.devtools.autosave.launchd'
    filename=$name.plist
    cp -v `dirname $0`/$filename "$launch_agents_dir"
    launchctl remove $name >/dev/null 2>/dev/null
    launchctl load "$launch_agents_dir/$filename"
elif [ -d /etc/init ]; then
    # Ubuntu
    cp -v `dirname $0`/autosave.conf /etc/init/
    start autosave
else
    echo 'Unsupported platform'
    exit 1
fi

**Comment by NV** [comment]
Fixed. Could you try to use it from the repo?

**Comment by drewcovi** [comment]
you rock. thanks! all good here.
