### ISSUE TITLE
Where are the routes stored by default?

### ISSUE THREAD

**Issue by simonexmachina** [NV/chrome-devtools-autosave-server#26]
I want to manage my routes in a json file, which I know is supported, but I'd like to get the ones that I've already configured in Chrome as a starting point. Where are these stored?

**Comment by NV** [comment]
The latest version of Autosave doesn’t store routes in JSON file. [Migration from pre 1.2 version](https://github.com/NV/chrome-devtools-autosave/wiki/Migration-from-pre-1.2-version). What exactly are you trying to achieve?

**Comment by simonexmachina** [comment]
I'd prefer to manage the routes in a JSON file. Primarily so that I can
control the order of the routes. But also because I'm a coder and have an
aversion to using the mouse :)

**Comment by NV** [comment]
Follow these instructions then https://github.com/NV/chrome-devtools-autosave/issues/7#issuecomment-3182946

**Comment by simonexmachina** [comment]
Great, thanks.

**Comment by NV** [comment]
I’ll close it then.
