### ISSUE TITLE
Config for routes

### ISSUE THREAD

**Issue by NV** [NV/chrome-devtools-autosave-server#3]
Users shouldn't have to edit [index.js](https://github.com/NV/chrome-devtools-autosave-server/blob/8d0abc00186d5d8e059e83821e6dfdaa0398309f/index.js#L23-28) just to add a new route.
NV/chrome-devtools-autosave#7

**Comment by sethburtonhall** [comment]
After creating the routes.js file, where should I put it?

**Comment by NV** [comment]
Wherever you want; you just need to pass a proper path to autosave. For example, routes.js in `/usr/local/devtools-autosave/routes.js` should be used like this: `autosave --config /usr/local/devtools-autosave/routes.js`.

**Comment by gg4u** [comment]
Hi, I placed routes in local dir of my site. When launching autosave with that dir, I have a node.js error " Cannot find module '/Users/name/routes.js"

If I place the routes under /Users/name/, it run with no error, but it does not actually save editing to css. No error in console.

Any clue?
On routes.js I placed localhost, not ^file://
If with file:// , I see messages reported on terminal console about successful editing, but i can't see no change on url page..

exports.routes = [
    {
        from: new RegExp('^http://localhost/~myname/blelbe/'),
        to: '/Users/myname/Sites/blelbe/'
    }
];

**Comment by gg4u** [comment]
Hello, I've found that:
exports.routes = [
    {
        from: new RegExp('^file:///Volumes/my_HD/Users/name/Sites/mysite/'),
        to: '/Volumes/my_HD/Users/name/Sites/mysite/'
    }
];

is saving properly and working only from URL
file:///Volumes/my_HD/Users/name/Sites/mysite/index2.html

I'd like to work from localhost, but It does not work if I change:

exports.routes = [
    {
        from: new RegExp('^http:///localhost/~/name/Sites/mysite/'),
        to: '/Volumes/my_HD/Users/name/Sites/mysite/'
    }
];

How to?
thank you very much! almost thtere!
